# Generated by Django 3.1.7 on 2021-04-06 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210401_0245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(max_length=50)),
                ('entertainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.profile')),
            ],
        ),
    ]
